/**
 * Loop Prevention Service
 * 
 * Prevents automation loops and recursion in webhook processing.
 * 
 * Features:
 * - Detects system-triggered messages
 * - Ignores messages generated by backend flows
 * - Stores last_action per subscriber to avoid recursion
 * - Rate-based loop detection
 * 
 * @author ScriptFlow Team
 * @version 1.0.0
 */

import { logger } from '../../utils/logger';
import { getRedis } from '../../queue/redis';

// ═══════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Result of loop detection check
 */
export interface LoopCheckResult {
    /** Whether the message should be processed */
    shouldProcess: boolean;

    /** Reason for blocking (if shouldProcess is false) */
    reason?: string;

    /** Type of loop detected */
    loopType?: 'system_message' | 'duplicate_action' | 'rate_loop' | 'backend_flow';

    /** Details for logging */
    details?: Record<string, unknown>;
}

/**
 * Last action record stored per subscriber
 */
export interface LastActionRecord {
    /** The action that was taken */
    action: string;

    /** Message hash that triggered the action */
    messageHash: string;

    /** Timestamp of the action */
    timestamp: number;

    /** Source of the action (user, system, backend) */
    source: 'user' | 'system' | 'backend';

    /** Request ID for tracing */
    requestId?: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// CONSTANTS
// ═══════════════════════════════════════════════════════════════════════════

/** Redis key prefix for last action */
const LAST_ACTION_KEY_PREFIX = 'loop:last_action:';

/** Redis key prefix for message rate tracking */
const MESSAGE_RATE_KEY_PREFIX = 'loop:rate:';

/** TTL for last action records (5 minutes) */
const LAST_ACTION_TTL_SECONDS = 5 * 60;

/** TTL for rate tracking (1 minute) */
const RATE_WINDOW_SECONDS = 60;

/** Maximum messages per minute before loop detection triggers */
const MAX_MESSAGES_PER_MINUTE = 30;

/** Minimum time between identical message hashes (in ms) */
const DUPLICATE_THRESHOLD_MS = 2000;

/** 
 * System-generated message patterns
 * These indicate the message was generated by ManyChat/backend, not user
 */
const SYSTEM_MESSAGE_PATTERNS: RegExp[] = [
    // ManyChat system keywords
    /^<mc_/i,                           // ManyChat internal tags
    /^\[SYSTEM\]/i,                     // System prefix
    /^\[AUTO\]/i,                       // Auto-generated prefix
    /^\[BOT\]/i,                        // Bot-generated prefix

    // Backend flow markers
    /^__FLOW__/i,                       // Internal flow marker
    /^__CALLBACK__/i,                   // Callback marker
    /^__TRIGGER__/i,                    // Trigger marker

    // Common ManyChat auto-responses
    /^<media:/i,                        // Media attachments from system
    /^<sticker:/i,                      // Stickers from system
    /^<reaction:/i,                     // Reactions from system
];

/**
 * Keywords that indicate a system/backend generated message
 */
const SYSTEM_KEYWORDS: string[] = [
    '__system__',
    '__backend__',
    '__auto__',
    '__flow__',
    '__trigger__',
    '__callback__',
    '__scriptflow__',
];

/**
 * Message sources that should be ignored
 */
const IGNORED_SOURCES: string[] = [
    'automation',
    'flow',
    'broadcast',
    'sequence',
    'bot',
    'system',
];

// ═══════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Generate a simple hash for a message
 */
function hashMessage(message: string): string {
    // Simple hash for deduplication (not cryptographic)
    let hash = 0;
    for (let i = 0; i < message.length; i++) {
        const char = message.charCodeAt(i);
        hash = ((hash << 5) - hash) + char;
        hash = hash & hash; // Convert to 32-bit integer
    }
    return hash.toString(16);
}

/**
 * Get Redis key for last action
 */
function getLastActionKey(subscriberId: string): string {
    return `${LAST_ACTION_KEY_PREFIX}${subscriberId}`;
}

/**
 * Get Redis key for rate tracking
 */
function getRateKey(subscriberId: string): string {
    return `${MESSAGE_RATE_KEY_PREFIX}${subscriberId}`;
}

// ═══════════════════════════════════════════════════════════════════════════
// LOOP PREVENTION SERVICE CLASS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * LoopPreventionService - Prevents automation loops and recursion.
 * 
 * This service should be called at the START of webhook processing
 * to determine if a message should be processed or ignored.
 * 
 * Detection methods:
 * 1. System message patterns - Messages generated by ManyChat system
 * 2. Backend flow markers - Messages from our own backend flows
 * 3. Duplicate action detection - Same action in short time window
 * 4. Rate-based loop detection - Too many messages in short time
 * 
 * @example
 * ```typescript
 * const check = await loopPrevention.checkForLoop({
 *   subscriberId: 'user123',
 *   rawMessage: 'some message',
 *   source: 'webhook',
 * });
 * 
 * if (!check.shouldProcess) {
 *   logger.info('Ignoring message due to loop detection', { reason: check.reason });
 *   return;
 * }
 * ```
 */
class LoopPreventionService {

    // ─────────────────────────────────────────────────────────────────────────
    // MAIN LOOP CHECK
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Check if a message should be processed or ignored due to loop detection.
     * 
     * OPTIMIZED: Uses Redis pipeline to batch rate + lastAction checks (reduces 5 calls to 1)
     * 
     * @param params - Check parameters
     * @returns LoopCheckResult indicating if message should be processed
     */
    async checkForLoop(params: {
        subscriberId: string;
        rawMessage: string;
        source?: string;
        requestId?: string;
        metadata?: Record<string, unknown>;
    }): Promise<LoopCheckResult> {
        const { subscriberId, rawMessage, source, requestId } = params;

        // ─────────────────────────────────────────────────────────────────────────
        // CHECK 1: System message pattern detection (NO Redis - pure regex)
        // ─────────────────────────────────────────────────────────────────────────
        if (this.isSystemMessage(rawMessage)) {
            logger.debug('[LoopPrevention] System message detected', {
                subscriberId,
                requestId,
                messagePreview: rawMessage.substring(0, 50),
            });

            return {
                shouldProcess: false,
                reason: 'Message appears to be system-generated',
                loopType: 'system_message',
                details: { messagePreview: rawMessage.substring(0, 50) },
            };
        }

        // ─────────────────────────────────────────────────────────────────────────
        // CHECK 2: Backend flow marker detection (NO Redis - pure regex)
        // ─────────────────────────────────────────────────────────────────────────
        if (this.isBackendFlowMessage(rawMessage)) {
            logger.debug('[LoopPrevention] Backend flow message detected', {
                subscriberId,
                requestId,
            });

            return {
                shouldProcess: false,
                reason: 'Message was generated by backend flow',
                loopType: 'backend_flow',
            };
        }

        // ─────────────────────────────────────────────────────────────────────────
        // CHECK 3: Ignored source detection (NO Redis - pure string check)
        // ─────────────────────────────────────────────────────────────────────────
        if (source && this.isIgnoredSource(source)) {
            logger.debug('[LoopPrevention] Message from ignored source', {
                subscriberId,
                source,
                requestId,
            });

            return {
                shouldProcess: false,
                reason: `Messages from source '${source}' are ignored`,
                loopType: 'backend_flow',
                details: { source },
            };
        }

        // ─────────────────────────────────────────────────────────────────────────
        // CHECK 4 & 5: PIPELINED Redis checks (rate + lastAction in 1 call)
        // OPTIMIZATION: Reduces 3 individual Redis calls to 1 pipeline
        // ─────────────────────────────────────────────────────────────────────────
        try {
            const redis = getRedis();
            const rateKey = getRateKey(subscriberId);
            const lastActionKey = getLastActionKey(subscriberId);

            // Pipeline: Fetch rate count AND last action in single round-trip
            const pipeline = redis.pipeline();
            pipeline.get(rateKey);
            pipeline.get(lastActionKey);
            const results = await pipeline.exec();

            // Parse pipeline results
            const rateCountRaw = results?.[0]?.[1] as string | null;
            const lastActionRaw = results?.[1]?.[1] as string | null;

            const currentRateCount = rateCountRaw ? parseInt(rateCountRaw, 10) : 0;
            const lastAction = lastActionRaw ? JSON.parse(lastActionRaw) as LastActionRecord : null;

            // CHECK 4: Rate limit
            if (currentRateCount >= MAX_MESSAGES_PER_MINUTE) {
                logger.warn('[LoopPrevention] Rate-based loop detected', {
                    subscriberId,
                    messageCount: currentRateCount,
                    requestId,
                });

                return {
                    shouldProcess: false,
                    reason: `Too many messages (${currentRateCount}/${MAX_MESSAGES_PER_MINUTE}) in the last minute`,
                    loopType: 'rate_loop',
                    details: { messageCount: currentRateCount, limit: MAX_MESSAGES_PER_MINUTE },
                };
            }

            // CHECK 5: Duplicate detection
            const messageHash = hashMessage(rawMessage);
            if (lastAction) {
                const timeSinceLastAction = Date.now() - lastAction.timestamp;

                if (lastAction.messageHash === messageHash && timeSinceLastAction < DUPLICATE_THRESHOLD_MS) {
                    logger.debug('[LoopPrevention] Duplicate message detected', {
                        subscriberId,
                        timeSinceLastAction,
                        requestId,
                    });

                    return {
                        shouldProcess: false,
                        reason: 'Duplicate message detected within threshold',
                        loopType: 'duplicate_action',
                        details: {
                            timeSinceLastAction,
                            threshold: DUPLICATE_THRESHOLD_MS,
                            lastAction: lastAction.action,
                        },
                    };
                }
            }

            // ─────────────────────────────────────────────────────────────────────────
            // ALL CHECKS PASSED - Increment rate counter (single optimized call)
            // ─────────────────────────────────────────────────────────────────────────
            // Use INCR + EXPIRE in pipeline for atomic increment
            const incrPipeline = redis.pipeline();
            incrPipeline.incr(rateKey);
            incrPipeline.expire(rateKey, RATE_WINDOW_SECONDS);
            await incrPipeline.exec();

            return {
                shouldProcess: true,
            };

        } catch (error) {
            logger.error('[LoopPrevention] Pipeline check failed, allowing message', { subscriberId, error });
            // Fail open - allow message if Redis is unavailable
            return { shouldProcess: true };
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // PATTERN DETECTION
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Check if message matches system message patterns
     */
    isSystemMessage(message: string): boolean {
        // Check regex patterns
        for (const pattern of SYSTEM_MESSAGE_PATTERNS) {
            if (pattern.test(message)) {
                return true;
            }
        }

        // Check keywords (case-insensitive)
        const lowerMessage = message.toLowerCase();
        for (const keyword of SYSTEM_KEYWORDS) {
            if (lowerMessage.includes(keyword)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Check if message is from a backend flow
     */
    isBackendFlowMessage(message: string): boolean {
        // Check for ScriptFlow-specific markers
        const markers = [
            '__scriptflow_generated__',
            '__sf_auto__',
            '<scriptflow:',
        ];

        const lowerMessage = message.toLowerCase();
        return markers.some(marker => lowerMessage.includes(marker));
    }

    /**
     * Check if source should be ignored
     */
    isIgnoredSource(source: string): boolean {
        return IGNORED_SOURCES.includes(source.toLowerCase());
    }

    // ─────────────────────────────────────────────────────────────────────────
    // LAST ACTION MANAGEMENT
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Get the last action for a subscriber
     */
    async getLastAction(subscriberId: string): Promise<LastActionRecord | null> {
        try {
            const redis = getRedis();
            const key = getLastActionKey(subscriberId);

            const data = await redis.get(key);
            if (!data) return null;

            return JSON.parse(data) as LastActionRecord;
        } catch (error) {
            logger.error('[LoopPrevention] Failed to get last action', { subscriberId, error });
            return null;
        }
    }

    /**
     * Store the last action for a subscriber
     */
    async setLastAction(
        subscriberId: string,
        action: string,
        messageHash: string,
        source: 'user' | 'system' | 'backend' = 'user',
        requestId?: string
    ): Promise<void> {
        try {
            const redis = getRedis();
            const key = getLastActionKey(subscriberId);

            const record: LastActionRecord = {
                action,
                messageHash,
                timestamp: Date.now(),
                source,
                requestId,
            };

            await redis.setex(key, LAST_ACTION_TTL_SECONDS, JSON.stringify(record));

            logger.debug('[LoopPrevention] Last action stored', {
                subscriberId,
                action,
                source,
            });
        } catch (error) {
            logger.error('[LoopPrevention] Failed to set last action', { subscriberId, error });
        }
    }

    /**
     * Clear the last action for a subscriber
     */
    async clearLastAction(subscriberId: string): Promise<void> {
        try {
            const redis = getRedis();
            const key = getLastActionKey(subscriberId);
            await redis.del(key);
        } catch (error) {
            logger.error('[LoopPrevention] Failed to clear last action', { subscriberId, error });
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // RATE TRACKING
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Check message rate for loop detection
     */
    private async checkMessageRate(subscriberId: string): Promise<{ allowed: boolean; count: number }> {
        try {
            const redis = getRedis();
            const key = getRateKey(subscriberId);

            const count = await redis.get(key);
            const currentCount = count ? parseInt(count, 10) : 0;

            return {
                allowed: currentCount < MAX_MESSAGES_PER_MINUTE,
                count: currentCount,
            };
        } catch (error) {
            logger.error('[LoopPrevention] Failed to check message rate', { subscriberId, error });
            // Fail open - allow the message if we can't check
            return { allowed: true, count: 0 };
        }
    }

    /**
     * Increment message rate counter
     */
    private async incrementMessageRate(subscriberId: string): Promise<void> {
        try {
            const redis = getRedis();
            const key = getRateKey(subscriberId);

            const exists = await redis.exists(key);

            if (exists) {
                await redis.incr(key);
            } else {
                await redis.setex(key, RATE_WINDOW_SECONDS, '1');
            }
        } catch (error) {
            logger.error('[LoopPrevention] Failed to increment message rate', { subscriberId, error });
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // UTILITY METHODS
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Generate a message hash for deduplication
     */
    hashMessage(message: string): string {
        return hashMessage(message);
    }

    /**
     * Get current rate count for a subscriber (for debugging/admin)
     */
    async getRateCount(subscriberId: string): Promise<number> {
        try {
            const redis = getRedis();
            const key = getRateKey(subscriberId);
            const count = await redis.get(key);
            return count ? parseInt(count, 10) : 0;
        } catch (error) {
            return 0;
        }
    }

    /**
     * Reset rate counter for a subscriber (for testing/admin)
     */
    async resetRateCounter(subscriberId: string): Promise<void> {
        try {
            const redis = getRedis();
            const key = getRateKey(subscriberId);
            await redis.del(key);
        } catch (error) {
            logger.error('[LoopPrevention] Failed to reset rate counter', { subscriberId, error });
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// SINGLETON INSTANCE
// ═══════════════════════════════════════════════════════════════════════════

export const loopPrevention = new LoopPreventionService();
export { LoopPreventionService };
export default loopPrevention;
